goplus/xgo

- qlang.v2/module2.go
fix bug: using plain(relative) file path, code at [qlang.v2/module2.go:44](https://github.com/qiniu/qlang/blob/develop/qlang.v2/module2.go#L44)
> Fix import package file path

- app/qexport/api.go
- app/qexport/main.go
通过go/api目录下 go(ver).txt 识别导出api的Go版本，并使用+build version 的方式导出，默认go1-go1.4算为base，而需要+build 导出的为 Go1.5和Go1.6版本。
> qexport support goapi version check, add +build verion export

- .travis.yml
- cl/stmt.go
- cl/stmt_test.go
- exec/golang/testdata/12.flow/flow.gop
make qgo support empty-switch and only-default-branch switch
```go
switch{}
switch v {
default:
println(v)
}
switch y:=v; y {
default:
println(y)
}
```
> Switch case fix

- .pre-commit-config.yaml
- .travis.yml
- go-imports prints no errors.
- no-go-testing prints no errors.
- go-cyclo shows a lot of errors until I set `-over` up to 100. **In future PRs, we should edit code to reduce the parameter down to about 20**.
> Enrich pre-commit hooks and call them from Travis CI

- .gitignore
- ast/ast_ql.go
- cmd/qfmt/qfmt.go
- exec/golang/internal/go/format/format.go
- exec/gop/format/format.go
- exec/gop/format/internal.go
- exec/gop/printer/nodes.go
- exec/gop/printer/printer.go
- some code come from golang source code
- only -w flag support for qfmt command, which is similar with the gofmt command
- test all tutorial gop script sucessfully
- add main and package for plain script, because of the parse will add the main and package information
- add Pos, End and exprNode function for ForPhrase, so it could be used as Expr interface
- no TernaryExpr support due to parser not supporting
> add qfmt to format goplus

- cmd/qexp/gopkg/exporter.go
- cmd/qexp/gopkg/exporter_test.go
```
import (
bar1 "foo/bar"
bar2 "abc/bar"
)
```
支持重命名的名称转换。
> cmd/qexp/gopkg: add fixPkgString and test

- token/position.go
- token/token.go
- Remove the comment of the source code block.
- Remove source code redundant with https://golang.org/src/go/token/token.go?s=5620:5653#L316
> Slight simplify source code of pakcage token

- cmd/qexp/gopkg/export.go
- cmd/qexp/gopkg/exporter_test.go
- cmd/qexp/qexport.go
move goplusRoot from cmd/qexp/gopkg to cmd/qexp,
add -outdir flag for customes set export lib path, default goplus/lib.
support multiple packages exported.
> cmd/qexp: add -outdir flag, format export pkg code.

- cmd/qexp/gopkg/export.go
- cmd/qexp/gopkg/exporter.go
- cmd/qexp/gopkg/exporter_test.go
- cmd/qexp/qexport.go
对 ConstUnboundInt 做检查，所以在 math 库中会出现 int64 和 uint64 转换。
（因为可能使用 gopherjs 32bit 编译，所以保留了 int64 转换）
```
I.Const("MaxInt32", qspec.ConstUnboundInt, math.MaxInt32),
I.Const("MaxInt64", qspec.Uint64, uint64(math.MaxInt64)),
I.Const("MaxInt8", qspec.ConstUnboundInt, math.MaxInt8),
I.Const("MaxUint16", qspec.ConstUnboundInt, math.MaxUint16),
I.Const("MaxUint32", qspec.Uint64, uint64(math.MaxUint32)),
I.Const("MaxUint64", qspec.Uint64, uint64(math.MaxUint64)),
I.Const("MaxUint8", qspec.ConstUnboundInt, math.MaxUint8),
I.Const("MinInt16", qspec.ConstUnboundInt, math.MinInt16),
I.Const("MinInt32", qspec.ConstUnboundInt, math.MinInt32),
I.Const("MinInt64", qspec.Int64, int64(math.MinInt64)),
I.Const("MinInt8", qspec.ConstUnboundInt, math.MinInt8),
I.Const("Phi", qspec.ConstUnboundFloat, math.Phi), …
```
> qexp: add export const and vars

- parser/parse.go
- parser/parser.go
The following function definitions are in file `parser/parse.go`; however, the only place to call them is `parser/parser.go`.
- `parser.parseSliceLit`
- `newSliceLit`
So, I am moving them from `parser/parse.go` to `parser/parser.go`.
> Move function definitions to where they are called

- parser/parse.go
By using `bytes.Buffer`, we avoid offset magic and error-prone offset values like `n+28`, `b[13:]`, `b[n+12]='\n'`.
> Use bytes.Buffer to avoid delicate offset operations

- cmd/qexp/gopkg/exporter.go
- cmd/qexp/gopkg/exporter_test.go
qexp 代码格式化调整为 goimports 样式，将 标准库和包含了 .-_  的导入行分开。
> cmd/qexp/gopkg: adjust import line (goimports style), fix #389

- cmd/qfmt/qfmt.go
format code from os.Stdin without do os.Exit 
use gofmt style to fix it
> format from source do os.Exit

- cmd/qexp/gopkg/export.go
- cmd/qexp/gopkg/exporter.go
- cmd/qexp/gopkg/exporter_test.go
- cmd/qexp/qexport.go
1. 忽略没有导出符号的 pkg, 如 hash 只包含 interface 接口，目前忽略导出。
2. 如果函数参数包含有未导出的 types.Named ，忽略此函数。 如 testing.MainStart(deps testing.testDeps, ...)
> cmd/qexp/gopkg: ignore empty exported pkg, ignore has unexported named param func

- cmd/qfmt/qfmt.go
- scanner/errors.go
- scanner/scanner.go
After some experiments in Go Playground, I realized that the `type A = B` syntax in Go is so straightforward that it makes the compiler literally considers A and B are exactly the same thing.
If we attach a method to A, we can call it with a receiver of type B.
If we define a function that accepts a parameter of type A, we can give it a variable of type B.
Then I realized that we can deduplicate pretty much code in package `scanner`.
> Deduplicate code in package scanner

- cmd/gop/main.go
- cmd/internal/base/base.go
- cmd/internal/export/export.go
- cmd/internal/gengo/go.go
- cmd/internal/help/help.go
- cmd/internal/run/run.go
`w io.Writer` is not used in `help.Help(w io.Writer, args []string)`, fix by pass `io.Writer` in all associated help info output function
> fix inconsistent command line output for different help info

- cmd/internal/export/export.go
- cmd/internal/export/gopkg/exporter.go
- cmd/internal/export/gopkg/exporter_test.go
之前在 https://github.com/goplus/gop/pull/507 时判断忽略导出 internal pkg 时引入错误，导制部分库会忽略导出。
现已修复此错误，并改用在函数导出参数时进行 internal pkg 判断。
fix ignore internal pkg export. 
```
qexp golang.org/x/tools@latest/go/packages/packagestest
ignore func (*golang.org/x/tools/go/packages/packagestest.Exported).Mark(name string, r golang.org/x/tools/internal/span.Range)
export "golang.org/x/tools/go/packages/packagestest" success
```
> cmd: export fix ignore internal import pkg bug

- cl/stmt.go
- cmd/internal/repl/replcmd.go
- repl/repl.go
```
$./igop
>>> 1+2
3
>>> a := 10
>>> a
10
>>> a+1
11
>>> fn := func(a int, b int) (int,int) { return a+b,a*b}
>>> fn
0x10d6890
>>> fn(10,20)
30
200
>>> c,d := fn(10,20)
>>> c
30
>>> d
200
>>> 
```
> repl: dump context return values

- cl/expr_test.go
- cl/gopkg_test.go
- cl/value.go
- cl/value_test.go
const int 类型在转换为 interface{} 调用时确定为 int 类型。
Go+ source
```
v := reflect.ValueOf(100)
println(v.Kind())
--------------- output
int
```
```
package main
import (
fmt "fmt"
reflect "reflect"
)
var v reflect.Value
func main() { 
//line ./main.gop:10
v = reflect.ValueOf(100)
//line ./main.gop:11
fmt.Println((reflect.Value).Kind(v))
}
```
已知问题：因为目前 const int 使用的是 int64/uint64 存储，所以在 interface{} 调用转换为 int 时检查 overflows 仅在 32 位环境（gophers)下有效，在 64 位下无效。
> cl: fix unbound const int call interface{} convert to int #514

- repl/repl.go
```
>>> println("hello world")
hello world
12,<nil>
>>> fn := func(a int,b int) (int,int) { return a+b,a*b}
>>> fn(10,20)
30,200
>>> 
```
> repl: dump context ret join by comma

- parser/parser.go
- token/token.go
```
$ igop
>>> 1/3r+1/4r*2
5/6
>>> 
```
> parser: fix #529 parseStmt support RAT operand

- cl/expr.go
- cl/expr_test.go
- exec/golang/builder.go
- exec/golang/builder_test.go
- exec/golang/testdata/28.method/method.gop
- exec/golang/type.go
- tutorial/26-Method/method.gop
support user-defined type convert
```
type M int
func (m M) Foo() {
println("foo", m)
}
m := M(0)
m.Foo()
println(m)
```
now:
```
[PANIC] github.com/goplus/gop/cl/expr.go:191: compileIdent failed: unknown - *cl.typeDecl
panic: compileIdent failed: unknown - *cl.typeDecl
```
fixed:
```
foo 0
0
```
> support user-defined type convert

- cl/compile.go
- cl/context.go
- cl/ctx_check.go
- cl/expr_test.go
- cl/stmt.go
- exec/golang/builder.go
- exec/golang/testdata/29.var-def/var_def.gop
cl: support var define
Go+ code
```
import "image"
type Point struct {
X int
Y int
}
var (
i,j,k int = 100,200,i+j
)
func main() {
var x = Point{10,20}
var pt image.Point
pt.X = 10
pt.Y = -10
println(i,j,k,x,pt)
}
```
generate Golang code error
```
package main
import (
fmt "fmt"
image "image"
)
type Point struct {
X int
Y int
}
var (
i int
j int
k int
)
func init() { 
//line ./main.gop:9
i = 100
//line ./main.gop:9
j = 200
//line ./main.gop:9
k = i + j
}
func main() {
var (
x  Point
pt image.Point
)
//line ./main.gop:14
x = Point{X: 10, Y: 20}
//line ./main.gop:16
pt.X = 10
//line ./main.gop:17
pt.Y = -10
//line ./main.gop:18
fmt.Println(i, j, k, x, pt)
}
```
> cl: support var define

- cl/expr_test.go
- cl/stmt.go
- exec/golang/func.go
- exec/golang/testdata/30.result/result.gop
Go+ code
```
import "fmt"
type Writer struct {
}
func (w *Writer) Write(data string) (n int, err error) {
return fmt.Println(data)
}
```
```
package main
import fmt "fmt"
type Writer struct {
}
var (
w   *Writer
err error
n   int
)
func main() { 
//line ./main.gop:8
w = &Writer{}
//line ./main.gop:9
n, err = w.Write("hello")
//line ./main.gop:10
fmt.Println(n, err)
}
func (recv *Writer) Write(_arg_0 string) (n int, err error) { 
//line ./main.gop:6
return fmt.Println(_arg_0)
}
```
> cl,golang: fix #581, compileReturnStmt result count check

- cl/context.go
- cl/expr.go
- cl/expr_test.go
- cl/stmt.go
- exec/golang/builder_test.go
- exec/golang/var.go
fix #606, support underscore
Go+ code
```
import (
"bytes"
"fmt"
)
var _ int
var _ int
var _ float32
var _ bytes.Buffer
_ = 100
_ = "hello"
_, n1 := 100,200
n2, _ := fmt.Println("Hello World")
println(n1,n2)
println("hello")
```
```
package main
import (
bytes "bytes"
fmt "fmt"
)
var (
_  bytes.Buffer
n1 int
n2 int
)
func main() { 
//line ./main.gop:11
_ = 100
//line ./main.gop:12
_ = "hello"
//line ./main.gop:13
_, n1 = 100, 200
//line ./main.gop:14
n2, _ = fmt.Println("Hello World")
//line ./main.gop:15
fmt.Println(n1, n2)
//line ./main.gop:16
fmt.Println("hello")
}
```
> fix #606, support underscore

- cl/expr_test.go
- cl/goinstr.go
- exec/bytecode/const_test.go
- exec/bytecode/goinstr_lstcompr_test.go
- exec/bytecode/var.go
goinstr
```
complex(1,2) => 1+2i
real(1+2i) => 1
imag(1+2i) => 2
```
> cl, bytecode: support complex goinstr

- ast/astutil/type.go
- cl/check_type.go
- cl/stmt_test.go
- exec/bytecode/goinstr_lstcompr.go
- exec/golang/testdata/32.channel/chan.gop
- exec/golang/type.go
fix #616 use reflect#value.Convert
```
intType := reflect.TypeOf(100)
t := reflect.ChanOf(reflect.BothDir, intType)
t1 := reflect.ChanOf(reflect.RecvDir, intType)
v := reflect.MakeChan(t, 10)
v1 := v.Convert(t1)
fmt.Println(v1.Type().ChanDir()) 
```
output
```
<-chan
```
> fix #616, support make unidirectional channel type

- cmd/gop/main.go
- cmd/internal/build/build.go
- cmd/internal/install/install.go
- cmd/internal/work/build.go
- cmd/internal/work/gengo.go
- cmd/internal/work/install.go
Execute the install command:
`gop install exec/golang/testdata/32.channel/chan.gop`
The generated binary file will be saved to env.GOPBIN. If there is no environment variable GOPBIN, save it to ~/gop/bin
Execute the build command:
`gop build exec/golang/testdata/32.channel/chan.gop -o <ouput>`
**Now the basic install and build are implemented（support single go file first）, but the buildflag is not implemented, and gengo also hopes to migrate to work.Gengo**
> support cmd gop install and gop build

- cl/context.go
- cl/expr.go
- cl/expr_test.go
use findMethod toptr to build GoPackage symbol ` (struct).method or (*struct).method`
```
// t is struct or interface
func findMethod(t reflect.Type, name string) (method reflect.Method, toptr bool, found bool) {
method, found = t.MethodByName(name)
if !found && t.Kind() == reflect.Struct {
t = reflect.PtrTo(t)
toptr = true
method, found = t.MethodByName(name)
}
return
}
```
> cl: compileSelectorExpr use better lookup method

- tutorial/20-Unix-Shebang/shebang
使用范例tutorial/20-Unix-Shebang/shebang无法运行，报错信息
```bash
/usr/bin/env: “gop run”: 没有那个文件或目录
/usr/bin/env: use -[v]S to pass options in shebang lines
```
我的环境
```bash
➜  ~ env --version
env (GNU coreutils) 8.30
Copyright (C) 2018 Free Software Foundation, Inc.
许可证 GPLv3+：GNU 通用公共许可证第 3 版或更新版本<https://gnu.org/licenses/gpl.html>。
本软件是自由软件：您可以自由修改和重新发布它。
在法律范围内没有其他保证。
由Richard Mlynarik、David MacKenzie 和Assaf Gordon 编写。
➜  ~ uname -a
Linux wurongjie-CO-PC 5.7.7-amd64-desktop #75 SMP Mon Aug 24 20:38:46 CST 2020 x86_64 GNU/Linux
```
根据man env说明，需要加`-S`参数，才能使用run参数在gop后面
> fix: Unix-Shebang范例无法运行

- ast/spec/lang_spec.go
- cl/goinstr.go
- cl/stmt_test.go
- exec/bytecode/chan.go
- exec/bytecode/chan_test.go
- exec/bytecode/var.go
Go+ code
```
c := make(chan int)
go close(c)
i := <- c
println(i) //output 0
```
```
package main
import fmt "fmt"
var (
c chan int
i int
)
func main() { 
//line ./main.gop:2
c = make(chan int)
//line ./main.gop:3
go close(c)
//line ./main.gop:4
i = <-c
//line ./main.gop:5
fmt.Println(i)
}
```
> cl, bytecode: support close goinstr

- cl/compile.go
- cl/compile_test.go
- repl/repl.go
fix #666
only support signal import line
```
import "path"
import name "path"
```
```
$ ./gop repl
Welcome to Go+ console!
>>> a := 10
>>> import "fmt"
>>> fmt.Println(a)
10
3,<nil>
>>> import "os"
>>> fmt.Fprintf(os.Stdout,"hello\n")
hello
6,<nil>
>>> 
```
> fix #666: import anytime for REPL

- cl/expr.go
- cl/expr_test.go
- cl/value.go
fix #657
fix #660
fix #661
Go+ code
```
import(
"sort"
)
// #657
ar := [1,5,3,2]
sort.IntSlice(ar).Sort()
println(ar)
// #660
i := 100
println(*(*int)(&i))
// #661
printf("%T\n",'a')
```
```
package main
import (
fmt "fmt"
sort "sort"
)
var (
ar []int
i  int
)
func main() { 
//line ./main.gop:6
ar = []int{1, 5, 3, 2}
//line ./main.gop:7
(sort.IntSlice).Sort(sort.IntSlice(ar))
//line ./main.gop:8
fmt.Println(ar)
//line ./main.gop:11
i = 100
//line ./main.gop:12
fmt.Println(*(*int)(&i))
//line ./main.gop:15
fmt.Printf("%T\n", int32(97))
}
```
> fix #657 #660 #661 type convert

- exec/golang/builder_test.go
- exec/golang/expr.go
fix https://github.com/goplus/gop/issues/652
exec/golang.Const 
val reflect.Type `Chan, Func, Map, Ptr, UnsafePointer, Interface, Slice` check is nil
> fix #652, func exec/golang.Const nil check

- cl/compile.go
- cl/expr.go
- cl/expr_test.go
- exec/golang/builder_test.go
- exec/golang/expr.go
fix #682 
fix #684 
- support constant declarations 
- predeclared identifier iota
- fix golang const float64 typecast
Go+ code
```
const Pi float64 = 3.14159265358979323846
const zero = 0.0         // untyped floating-point constant
const (
size int64 = 1024
eof        = -1  // untyped integer constant
)
const va, vb, vc = 3, 4, "foo"  // a = 3, b = 4, c = "foo", untyped integer and string constants
const fu, fv float32 = 0, 3    // u = 0.0, v = 3.0
const (
c0 = iota  // c0 == 0
c1 = iota  // c1 == 1
c2 = iota  // c2 == 2
)
const (
a = 1 << iota  // a == 1  (iota == 0)
b = 1 << iota  // b == 2  (iota == 1)
c = 3          // c == 3  (iota == 2, unused)
d = 1 << iota  // d == 8  (iota == 3)
)
const (
u         = iota * 42  // u == 0     (untyped integer constant)
v float64 = iota * 42  // …
```
> cl: support const & iota

- cl/check_type.go
- cl/expr.go
- cl/expr_test.go
- cl/goinstr.go
- cl/value.go
- exec.spec/interface.go
- exec/bytecode/interface.go
- exec/bytecode/operator.go
- exec/golang/builder.go
- exec/golang/builder_test.go
- exec/golang/interface.go
- exec/golang/testdata/33.left-shift/left_shift.gop
fix #685
https://golang.google.cn/ref/spec#Operators
Go+ code
```
func test1(v int) {
printf("test1 %v %T\n", v, v)
}
func test2(v int32) {
printf("test2 %v %T\n", v, v)
}
func test3(v int64) {
printf("test3 %v %T\n", v, v)
}
func test4(v ...int32) {
printf("test4 %v %T\n", v, v)
}
var a [1024]byte
var s uint = 33
var q int16
// The results of the following examples are given for 64-bit ints.
var i = 1 << s         // 1 has type int
var j int32 = 1 << s   // 1 has type int32; j == 0
var k = uint64(1 << s) // 1 has type uint64; k == 1<<33
var m int = 1.0 << s   // 1.0 has type int; m == 1<<33
var n = 1.0<<s == j    // 1.0 has type int; n == true
var o = 1<<s == 2<<s   // 1 and 2 have type int; o == false
var p = 1<<s == 1<<33  // 1 has type int; p == true
// var u = 1.0<<s …
```
> shift operations type check

- cmd/internal/base/gocmd.go
- cmd/internal/build/build.go
- cmd/internal/install/install.go
Motivation:
gop does not implement `build` command yet.
Design:
`build` command is almost like install command, so I put the common parts into base package :
1. common arguments parsing
2. go code generating and pkgs caching
> [WIP]implement build command

- ast/ast.go
- ast/filter.go
- cl/compile.go
- cl/error_msg_test.go
- parser/parser_gop.go
src1
```
println a
```
adjust **gop/cl** pos column 
```
./hello.gop:1:9: undefined: a
```
src2
```
func foo() {}
foo(1)
```
adjust **gox** pos column
```
hello.gop:3:1: too many arguments in call to foo(1)
have (untyped int)
want ()
```
> adjust cl and gox error column no entry

- ast/ast.go
- cl/compile.go
- cl/compile_test.go
- cmd/gengo/gen.go
- cmd/goptestgo/goptestgo.go
- cmd/internal/run/run.go
- go.mod
- go.sum
- parser/_testdata/funcdoc/funcdoc.gop
- parser/_testdata/funcdoc/parser.expect
- parser/_testdata/mytest/parser.expect
- parser/parser_test.go
- parser/parserdir_test.go
- parser/parsertest/parsertest.go
> support function instruction

- x/mod/internal/lazyregexp/lazyregexp.go
- x/mod/modfile/print.go
- x/mod/modfile/read.go
- x/mod/modfile/rule.go
- x/mod/modfile/rule_test.go
The syntax tree of this gop.mod file can be defined as
```golang
// A File is the parsed, interpreted form of a gop.mod file.
type File struct {
Module    *Module
Go        *Go
Gop       *Gop
Classfile *Classfile
Register  *Register
Require   []*Require
Exclude   []*Exclude
Replace   []*Replace
Retract   []*Retract
Syntax *FileSyntax
}
// A Gop is the gop statement.
type Gop struct {
Version string // "1.23"
Syntax  *Line
}
// A Classfile is the classfile statement.
type Classfile struct {
ProjExt  string   // ".gmx"
WorkExt  string   // ".spx"
PkgPaths []string // paths of classfile
Syntax   *Line
}
// A Register is the register statement.
type Register struct {
ClassfileMod string // modname of classfile
Syntax       *Line
}
```
If the content of the gop.mod file is
```
module spx
go …
```
> Add modfile package which can be used to parse gop.mod

- cl/compile_test.go
- cl/error_msg_test.go
- cl/expr.go
1.  fix lambda for named func call
```
type Fn func() (int, error)
func Do(fn Fn) {
v, err := fn()
println(v, err)
}
Do => {
return 100, nil
}
```
2. fix  lambda result type for untyped
```
- func compileLambdaExpr(ctx *blockCtx, v *ast.LambdaExpr, in *types.Tuple)
+ func compileLambdaExpr(ctx *blockCtx, v *ast.LambdaExpr, in *types.Tuple, out *types.Tuple)
```
3. check lambda and panic
```
func foo(int) {
}
foo(=> {})
```
```
main.gop:3:5: cannot use lambda literal as type int in argument to foo
```
> cl: fix lambda for named func call, fix  lambda result untyped check.

- cl/compile_test.go
- cl/error_msg_test.go
- cl/expr.go
- parser/_testdata/lambda4/lambda4.gop
- parser/_testdata/lambda4/parser.expect
- parser/parser.go
fix https://github.com/goplus/gop/issues/933
key:value only
```
type Foo struct {
Plot func(x float64) (float64, float64)
}
foo := &Foo{
Plot: x => (x * 2, x * x),
}
bar := &Foo{
Plot: x => { 
return x * 2, x * x
},
}
```
> cl: support lambda in struct literal 

- .github/workflows/go.yml
Setup CI for windows and mac platforms, test with Go 1.16 and 1.17.
> Setup CI for windows and mac platforms

- parser/parser.go
- parser/parser_test.go
parser add toIdent check and dump error.
```
func test(v string, f func( int)) {
f(100)
}
test "hello" => {
println "lambda",x
}
```
```
main.gop:5:6: expected 'IDENT', found "hello"
```
> parser: check toIdent error

- cmd/internal/build/build.go
- cmd/internal/help/help.go
- cmd/internal/mod/init.go
- cmd/internal/modload/modload.go
- x/mod/modfile/rule.go
modify the 'go' in the usage and error prompts to 'gop'
> usage help and error prompt

- cl/compile.go
- cl/compile_spx_test.go
fix https://github.com/goplus/gop/issues/978
```
var (
a = 100
b int = 100
)
println "hi"
```
```
index.gmx:2:2: missing field type in class file
index.gmx:3:2: cannot assign value to field in class file
```
> cl: class file check field spec type and value

- .github/workflows/release-build.yml
- Makefile
- cmd/install.go
* `cmd/install.go` set `defaultGopRoot` to `$GOPROOT_FINAL` if provided
* Build to the bin/ directory correctly
* Build 9 targets with the new build script
> Build multi platform target

- cmd/internal/modload/classfile.go
when the gop operation is inconsistent with the gop.mod directory, the file cannot be obtained by gop.mod
> fix the problem that the path to get the class file gop.mod is wrong

- x/format/README.md
* Convert `fmt.Errorf => errorf`
* Convert `fmt.Fprint => fprint`
* Convert `fmt.Fprintf => fprintf`
* Convert `fmt.Fprintln => fprintln`
* Convert `fmt.Print` => `print`
* Convert `fmt.Printf` => `printf`
* Convert `fmt.Println` => `println`
* Convert `fmt.Sprint => sprint`
* Convert `fmt.Sprintf => sprintf`
* Convert `fmt.Sprintln => sprintln`
> docs: update readme for print functions replacement

- cl/compile.go
- cl/expr.go
- cl/func_type_and_var.go
> replace bc.imports[] with findImport

- README.md
- README_zh.md
Add workarounds to the following issues
`build github.com/goplus/gop/cmd/gop: cannot load io/fs: malformed module path "io/fs": missing dot in first path element`
> supplement readme for io/fs issue

- cmd/make.go
- cmd/make_test.go
* Support execute `go run cmd/make.go --tag <next-version>` command on ** any git branch** to release a new version of `gop`.
* The new version can be used by following Go+ build process.
* Full testcases to make sure it will do what that we expected.
* To build the Go+, the dir is requied to be a git repo or a `VERSION` file exists.
0. The command could be executed on any git branch, the command will checkout to target release branch and checkout back to source branch automatically.
1. Store `new-version` into `VERSION` file, which can also be submitted to git repo, and will be kept on a release branch.
2. Auto execute `git tag new-version` command to tag the source code.
> Add release tool

- cmd/internal/run/run.go
- x/gopproj/gopproj.go
1. gop run localdir
- store current dir to _wd_
- change current  dir to localdir for go.mod
- gen go code
- reset  go run dir to _wd_
2. gop run pkg
- store current dir to _wd_
- change current to `GOMODCACHE` for go.mod
- gen go code
- reset  go run dir to _wd_
> x/gopproj: fix gop run workdir

- cmd/internal/run/run.go
- x/gopproj/gopproj.go
remove reduplicate error
```
newImporter: [github.com/goplus/gop/builtin os strconv strings]
github.com/visualfc/gopdemo
compile: ./main.gop:4:9: undefined: err
OpenProject failed: compile: ./main.gop:4:9: undefined: err
```
simply to
```
newImporter: [strconv strings github.com/goplus/gop/builtin os]
github.com/visualfc/gopdemo
compile: ./main.gop:4:9: undefined: err
```
> gop run remove reduplicate error

- cl/error_msg_test.go
- cl/func_type_and_var.go
fix https://github.com/goplus/gop/issues/1060
```
type Id struct {
}
type A struct {
Id
Id   int
Id   string
name string
name string
}
```
error message compatible for **Go1.18** compile error message.
```
./bar.gop:6:2: Id redeclared
./bar.gop:5:2 other declaration of Id
./bar.gop:7:2: Id redeclared
./bar.gop:5:2 other declaration of Id
./bar.gop:9:2: name redeclared
./bar.gop:8:2 other declaration of name
```
not used **Go1.16** compile error message.
```
./bar.go:13:2: duplicate field Id
./bar.go:14:2: duplicate field Id
./bar.go:16:2: duplicate field name
```
> cl: check struct type fields name redeclared

- cl/compile.go
- cl/compile_spx_test.go
- cl/compile_test.go
fix https://github.com/goplus/gop/issues/1017
`cl.Config add NoAutoGenMain bool`
**empty .gop**
```
//blink
```
generate to
```
package main
func main() {
}
```
**no entry .gop**
```
func test() {
println "hello"
}
```
generate
```
package main
import fmt "fmt"
func test() {
fmt.Println("hello")
}
func main() {
}
```
**no entry index.gmx**
```
var (
Calf Calf
)
```
generate 
```
package main
import spx "github.com/goplus/spx"
type index struct {
spx.Game
Calf Calf
}
type Calf struct {
spx.Sprite
*index
}
func (this *index) MainEntry() {
}
func main() {
spx.Gopt_Game_Main(new(index))
}
```
>  cl: config add NoAutoGenMain for auto generate main func if no entry

- cl/compile_test.go
- cl/error_msg_test.go
- cl/stmt.go
> fix #1228, lamda support in return statement

- cl/stmt.go
// main.gop
```
for i <- :10, i%3 == 0 {
println i
}
```
// go run main.gop bug
```
main.gop:2: invalid line number: 0
```
this PR fixed but gop fmt this file to
```
for i <- :10 if i%3 == 0 {
println i
}
```
> cl: fix #1243 for rangeExpr if pos

- cl/compile.go
- cl/compile_test.go
fix mixed .go and .gop
cl preloadFile restore current file.
> cl: preloadFile restore cur file

- parser/parser.go
- parser/parser_test.go
```
println (1,2)*2
```
`main.gop:1:9: tuple is not supported`
> parser: parseBinaryExpr check tuple

- README.md
goplus can be installed for both macOS and Linux, https://formulae.brew.sh/formula/goplus
fixes #1349
> docs:  update homebrew install note

- cl/compile_test.go
- cl/expr.go
fix https://github.com/goplus/gop/issues/1367
```
func CreateBox(name string, opt Option) {
println(name,opt)
}
CreateBox("box",{Size:1}) // ok
CreateBox("box",{}) // fixed build pass
```
> fix empty struct argument call for gop style

- cl/compile.go
- cl/error_msg_test.go
fix #1369 , loadVars check recover and resetInit
```
func set(name string, v int) string {
return name
}
func test() {
var a = set("box")  // dump error
println(a)
}
```
`gop run` can dump error info
```
./main.gop:6:10: too few arguments in call to set("box")
have (untyped string)
want (name string, v int)
./main.gop:7:10: undefined: a
```
> cl: loadVars check recover

- cmd/gopfmt/gopfmt.go
- cmd/internal/gopfmt/fmt.go
- format/format.go
- format/internal.go
- load.go
- printer/gop_test.go
gop fmt and gopfmt support lookup classfile
- support load classfile from gopmod
- support classfile embed type
- add .gopx
> gopfmt: support classfile

- ast/ast.go
- cl/compile.go
- cl/compile_spx_test.go
- cl/compile_test.go
- cl/error_msg_test.go
- parser/_testdata/gopxtest/bar.gopx
- parser/_testdata/gopxtest/parser.expect
- parser/parser.go
- parser/parser_test.go
- printer/nodes.go
classfile embed type support starExpr and selectorExpr
Rect.gopx
``` 
import "bytes"
var (
*bytes.Buffer
My
x, y int
)
```
generate:
```
type Rect struct {
*bytes.Buffer
My
x int
y int
}
```
> parser/cl: classfile support embed type starExpr and selectorExpr

- builtin/ng/int128.go
- builtin/ng/uint128.go
- cl/error_msg_test.go
fix https://github.com/goplus/gop/issues/1323
> builtin: compiler check untyped overflows for int128/uint128

- .gitattributes
- ast/ast.go
- cl/compile.go
- cl/compile_test.go
- parser/_testdata/gopxtest/bar.gopx
- parser/_testdata/gopxtest/parser.expect
- parser/parser.go
- printer/gop_test.go
- printer/nodes.go
support .gopx classfile field tag
Rect.gopx
```
import "bytes"
var (
*bytes.Buffer "spec:\"buffer\""
a int "json:\"a\""
b int
)
func test(){}
```
autogen_gop.go
```
package main
import bytes "bytes"
type Rect struct {
*bytes.Buffer "spec:\"buffer\""
a             int "json:\"a\""
b             int
}
func (this *Rect) test() {
}
```
> classfile field var support tag

- cmd/make.go
hello, thank you so much for this project 👍🏻
a [previous commit](https://github.com/goplus/gop/pull/1387/commits/c45906e8fbd1f5611a1222204724822260037182) by @92hackers set this conditional to return as `true` when the observed windows locale contains `zh-hk`, and then applies `GOPROXY` setting based on such detection.
the flag is supposed to _Set GOPROXY for people in China_ ([source code](https://github.com/goplus/gop/blob/main/cmd/make.go#L550)). if this flag is truthy, the proxy `goproxy.cn` is used, which would, in effect, redirect HK users traffic.
> fix: hong kong locale does not always mean china

- cl/expr.go
https://github.com/goplus/gop/issues/1240 check typetype  must on args.
```
type fvec []float64
fvec([1, 2])
```
> cl: compileCallExpr check one arg for ast.SliceLit

- cl/compile_test.go
- cl/expr.go
fix https://github.com/goplus/gop/issues/1414
> cl: compileIdent class remove clCommandWithoutArgs

- cl/error_msg_test.go
- cl/expr.go
check compile func internal error.
```
printf("%+v\n", int32)
```
> cl: fix compileCallArgs recover check

- parser/_instance/instance5/cmd.gop
- parser/_instance/instance5/parser.expect
- parser/parser.go
fix https://github.com/goplus/gop/issues/1492
> parser: parsePrimaryExpr fix LiteralValue check

- cl/compile.go
- cl/error_msg_test.go
- cl/func_type_and_var.go
- cl/outline/cl/compile.go
- cl/outline/cl/error_msg_test.go
- cl/outline/cl/func_type_and_var.go
- toStructType add field pos
- toStructType record field
- loadFunc fix name pos
> toStructType: add field pos and record.Def field

- parser/parser.go
- parser/parser_test.go
fix https://github.com/goplus/gop/issues/1505
> parser: parseGlobalStmts EOF check

- cmd/internal/build/build.go
- cmd/internal/doc/doc.go
- cmd/internal/gengo/go.go
- cmd/internal/install/install.go
- cmd/internal/run/run.go
- cmd/internal/test/test.go
- gengo.go
- go.mod
- go.sum
- load.go
- outline.go
- token/internal/tokenutil/lines_go118.go
- token/internal/tokenutil/lines_go120.go
- token/internal/tokenutil/lines_go121.go
- token/internal/tokenutil/lines_test.go
- token/types.go
- https://github.com/goplus/gox/pull/302
> gop go -ignore-notated-error

- cl/compile.go
- cl/expr.go
- cl/func_type_and_var.go
- cl/internal/typesutil/api.go
- cl/internal/typesutil/api_test.go
- x/typesutil/info_test.go
cl/internal/typesutil: update TypeAndValue
fix https://github.com/goplus/gop/issues/1537
```
package main
type Person struct {
name string
age  int8
}
func test() {
p := Person{
name: "jack",
}
_ = p.name
}
```
```
info_test.go:106: ====== check types pass (count: 8) ======
000:  3:13 | struct {
name string
age  int8
} *ast.StructType                | type    : struct{name string; age int8} | type
001:  4: 7 | string              *ast.Ident                     | type    : string | type
002:  5: 7 | int8                *ast.Ident                     | type    : int8 | type
003:  9: 7 | Person              *ast.Ident                     | type    : main.Person | type
004:  9: 7 | Person{
name: "jack",
} *ast.CompositeLit              | value   : main.Person | value
005: 10: 9 | "jack" …
```
> typesutil: update TypeAndValue

- cmd/make.go
`gop version` output incorrect tag version if the binary installation via source code as below:
```
➜  gop git:(main) gop version
gop v1.1.3-577-g4cf8b5e9 darwin/amd64
```
Now, This behavior will be adjusted to:
```
➜  gop git:(fix_version) gop version
gop v1.1.13 devel darwin/amd64
```
> chore: use the latest tag version and append it with "devel" to signify the binary installation via source code

- cmd/make.go
> fix: fix bugs when checking if symbolic link path exists

- cl/compile_spx_test.go
- cl/compile_test.go
- cl/expr.go
- cl/internal/overload/foo/foo.go
- cl/internal/spx/sprite.go
- support TyTemplateRecvMethod overload funcs
- fix lambda variadic func call 
eg. ( func OnKey__9(a, b string, fn ...func(x int) int) )
> cl: fnType support TyTemplateRecvMethod overload funcs

- .github/workflows/release-build.yml
- .goreleaser.yaml
- README.md
* rename winget package name to goplus to supports `winget install goplus`, also supports `winget install goplus.gop`
* rename deb/rpm/snapcraft package name to gop
* publish deb/rpm to fury.io
* update installation docs
> Pkg publish

- cl/compile.go
- go.mod
- go.sum
- x/typesutil/check_test.go
- x/typesutil/gopinfo.go
- x/typesutil/info_test.go
```
type Info struct {
...
// Overloads maps identifiers to the overload objects.
Overloads map[*ast.Ident][]types.Object
}
```
> x/typesutil: info.Overloads

- cmd/internal/gengo/go.go
This PR primarily addresses the following two issues.
* `gop go` doesn't support convert go+ files into go, fox example:
```shell
➜  101-Hello-world git:(main) ✗ gop go -v hello-1.gop
2024/02/02 16:53:22 SetDebug: import=true, match=true, instr=true
2024/02/02 16:53:22 `gop go` doesn't support *gopprojs.FilesProj
panic: `gop go` doesn't support *gopprojs.FilesProj
goroutine 1 [running]:
log.Panicln({0xc000205e28?, 0xc0000ba060?, 0x1d045b8?})
/opt/hostedtoolcache/go/1.21.6/x64/src/log/log.go:446 +0x5a
github.com/goplus/gop/cmd/internal/gengo.runCmd(0xc0000d8000?, {0xc0000ba060?, 0x0?, 0xc00006a688?})
/home/runner/work/gop/gop/cmd/internal/gengo/go.go:92 +0x365
main.main()
/home/runner/work/gop/gop/cmd/gop/main.go:113 +0x4b3
```
* The original single file mode flag `-s` seems aim to work in …
> feat(gengo): support convert go+ files into go code

- .github/workflows/release-build.yml
- .goreleaser.yaml
* Skip publish prerelease version to winget/fury.io because winget/yum/apt are incompatible with SemVer.
* Enable winget PR draft
> ci: skip publish prerelease

- cl/compile_gop_test.go
- cl/expr.go
old implementation: https://github.com/goplus/gop/pull/1692
> mayBuiltin new/delete

- parser/parser.go
- parser/parser_test.go
fix parser panic 
```
run "
```
```
panic: runtime error: slice bounds out of range [1:0] [recovered]
panic: runtime error: slice bounds out of range [1:0]
goroutine 1 [running]:
github.com/goplus/gop/parser.parseFile.func1()
/Users/vfc/goplus/gop/parser/interface.go:96 +0x1f2
panic({0x1680080?, 0xc0000c81c8?})
```
fixed to
```
bug.gop:1:5: string literal not terminated
```
> parser: fix string extra check

- cl/compile_gop_test.go
- cl/compile_test.go
- go.mod
- go.sum
https://github.com/goplus/gop/issues/1761
> deps: update gox because fix  issue-1761

- .github/workflows/release-build.yml
- .goreleaser.yaml
- Dockerfile
Fixes #1818
---
Note that this feature requires the [Workflow permissions](https://github.com/goplus/gop/settings/actions) to be set to `Read and write permissions`.
> Introduce official Docker image

- doc/contributing.md
As our project grows, we want to ensure that our community understands how to contribute effectively and feels welcomed to do so. This update to our contribution guidelines aims to clarify the process and encourage more developers to get involved.
Key changes include:
- Simplified the language to make the guidelines more accessible to non-native English speakers and newcomers to open source.
- Included a step-by-step guide on setting up the development environment, submitting a pull request, and what to expect during the review process.
- Added a new section on community standards and code of conduct to foster a respectful and inclusive community atmosphere.
- Provided clear examples of desirable contributions, such as bug fixes, feature proposals, and documentation improvements.
Updates …
> docs: revise contribution guidelines for clarity and inclusivity

- cl/expr.go
- cl/typeparams_test.go
- go.mod
- go.sum
fix https://github.com/goplus/gop/issues/1765
> generic func infer lambda expr

- cl/compile.go
- cl/compile_gop_test.go
```go
// origin.gop
func MulInt(a,b int) int  {
return a * b
}
func MulFloat(a,b float64) float64  {
return a * b
}
func Mul = (
func(a string,b string){}
MulInt
MulFloat
)
```
The overloaded function declaration generated in the previous version lacks the location of the anonymous overloaded function.
```go
// before autogen.go
const _ = true
const Gopo_Mul = "MulInt,MulFloat"
func Mul__0(a string, b string) {
}
func MulInt(a int, b int) int {
return a * b
}
func MulFloat(a float64, b float64) float64 {
return a * b
}
```
```go
// current autogen.go
const _ = true
const Gopo_Mul = ",MulInt,MulFloat"
....
```
> update:correct anonymous overloaded function naming

- .github/workflows/go.yml
This update ensures that Go+ CI is triggered by pushes and pull requests to all branches, providing comprehensive coverage across the repository. This change is particularly beneficial for enabling GitHub Actions in forks, facilitating a more seamless development and testing process.
> ci: update workflow to trigger on pushes and PRs to any branches

- .goreleaser.yaml
Following the changes introduced in #1838, this commit updates Docker image and manifest tags to align with the GoReleaser artifact naming conventions. The changes are as follows:
- Image tags have been updated from "v1.2.3-i386" to "1.2.3-386", from "v1.2.3-x86_64" to "1.2.3-amd64", "v1.2.3-arm64" to "1.2.3-arm64".
- The version prefix "v" has been removed from the image manifest tags, changing "v1.2.3" to "1.2.3", "v1.2" to "1.2", and "v1" to "1".
---
Should we keep the `v` prefix? I referred to the tag style of `docker.io/library/golang` and removed the `v` prefix. (See: https://hub.docker.com/_/golang/tags?name=-alpine3.19)
/cc @xushiwei @cpunion
> docker: align image tags with GoReleaser artifacts

- ast/ast.go
- cl/builtin_test.go
fix (*ast.File).End bad result if classfile add shadow func Classfname.
example `get.yap` ast.File.End return  last shadow func Classfname.End()
> ast: fix (*ast.File).End check shadow no entry

- x/typesutil/check_test.go
- x/typesutil/gopinfo.go
- x/typesutil/info_test.go
modify info.Overloads to point to the overload decl instead point to overload member
```go
type Info struct {
...
// Overloads maps identifiers to the overload decl object.
Overloads map[*ast.Ident][]types.Object
}
```
and modify the use of info.Overload in tools in this PR [https://github.com/goplus/tools/pull/270](https://github.com/goplus/tools/pull/270)
> x/typesutil:modify info.Overloads to point to the overload decl

- cl/compile.go
- cl/compile_spx_test.go
- x/typesutil/info_test.go
#1874  
The overloaded function declaration in classfile will eventually become an overloaded method of type classfile
`Rect.gox`
```go
func addString(a, b string) string {
return a + b
}
func addInt(a, b int) int {
return a + b
}
func add = (
addInt
addString
)
```
`autogen.go`
```go
package main
const Gopo_Rect_add = ".addInt,.addString"
type Rect struct {
}
func (this *Rect) addString(a string, b string) string {
return a + b
}
func (this *Rect) addInt(a int, b int) int {
return a + b
}
```
> update:support declared function in classfile's overload decl

- Dockerfile
> docker: remove gopfmt from the baked Docker image

- cmd/make_test.go
This follows up on #1930.
For https://github.com/goplus/gop/actions/runs/9927782432/job/27423172805#step:4:27
```
=== RUN   TestInstallInNonGitRepo/install_with_VERSION_file
make_test.go:324: Failed: exit status 2, output: panic: gop/env: [FATAL] Invalid buildVersion: v1.2.98
goroutine 1 [running]:
github.com/goplus/gop/env.initEnv()
/home/runner/work/gop/gop/env/version.go:47 +0x8a
github.com/goplus/gop/env.init.0()
/home/runner/work/gop/gop/env/version.go:38 +0xf
```
> test: make cmd/TestInstallInNonGitRepo not affected by actual major.minor versions

- cl/compile_test.go
- cl/stmt.go
- demo/sliceliteral/sliceliteral.gop
fix https://github.com/goplus/gop/issues/1954
> cl: fix slicelit for assignStmt/returnStmt

- cl/compile_test.go
- cl/error_msg_test.go
- cl/expr.go
- cl/stmt.go
compileCompositeLitEx
- struct
```
type T struct {
s  []any
m  map[any]any
fn func(int) int
}
echo &T{[10, 3.14, 200], {10: "A", 3.14: "B", 200: "C"}, (x => x)}
echo &T{s: [10, 3.14, 200], m: {10: "A", 3.14: "B", 200: "C"}, fn: (x => x)}
```
- slice/map
```
var a [][]any = {[10, 3.14, 200], [100, 200]}
var m map[any][]any = {10: [10, 3.14, 200]}
var f map[any]func(int) int = {10: x => x}
```
> cl: fix compileCompositeLitEx struct for sliceLit/mapLit

- .goreleaser.yaml
- Dockerfile
According to GoReleaser docs, the directory names inside dist have no guarantee of remaining the same across different GoReleaser versions[^1]. Therefore, we extract from tarballs instead of using those directories directly.
[^1]: https://goreleaser.com/customization/builds/#a-note-about-directory-names-inside-dist
> fix(Dockerfile): extract artifacts from tarball when using GoReleaser

- x/format/_testdata/collection/format.expect
- x/format/gopstyle_test.go
- x/format/stmt_expr_or_type.go
format funclit to lambda expr
```
println(demo(func(n int) int {
return n+100
}))
println(demo(func(n int) int {
println(n)
return n+100
}))
println(demo(func(n int) (v int) {
return n+100
}))
demo2(300, func(n1, n2 int) int {
return n1 + n2
})
demo2(300, func(int, int) int {
println("hello")
return 600
})
```
format to lambda ( skip named results )
```
println demo(n => n + 100)
println demo(n => {
println n
return n + 100
})
println demo(func(n int) (v int) {
return n + 100
})
demo2 300, (n1, n2) => n1 + n2
demo2 300, (_, _) => {
println "hello"
return 600
}
```
> x/format: funcLitToLambdaExpr

- ast/walk.go
- Replaced multiple type-specific `walkXList` helper funcs with a single generic `walkList[N Node]` func.
- Added `TypeParams` handling for `FuncType` and `TypeSpec`.
- Improved nil-safety with additional checks.
> refactor(ast): improve `Walk` with latest `go/ast.Walk`

- go.mod
- go.sum
- x/typesutil/check.go
- x/typesutil/check_test.go
> refactor(x/typesutil.Checker): handle `gogen.BoundTypeError` with fallback error logic

- cl/compile_test.go
- cl/expr.go
```
echo foo! => echo foo()!
```
> cl: compileErrWrapExpr check callExpr

- cl/builtin_test.go
- cl/classfile.go
- cl/compile.go
- cl/compile_spx_test.go
- cl/internal/spx3/spx3.go
- x/build/build_test.go
- x/typesutil/info_test.go
> classfile support auto-generated clone

- .github/workflows/go.yml
- cl/builtin.go
- cl/cltest/cltest.go
- cl/compile.go
- cl/compile_gop_test.go
- cl/compile_test.go
- cl/typeparams_test.go
- x/typesutil/info_test.go
- cl enable gotypesalias by check `builtin/ng.Gop_ninteger` not *types.Basic (*types.Alias)
- cl record alias type
- x/typesutil support alias type
- workflows: TestTypeAlias ( Go1.23/Go1.24 and golang.org/x/tools v0.30 )
> support gotypesalias

- cmd/make.go
- tool/imp.go
- make.go check go1.24 use go.work mode
- importer cache file hash add runtime.Version()
> make: support Go1.24

- ast/ast.go
- cl/compile_spx_test.go
- cl/expr.go
- cl/internal/spx4/game.go
- cl/stmt.go
fix: https://github.com/goplus/builder/issues/1696
> fix(compile): ensure valid Rparen and NoParenEnd in CallExpr

- cl/stmt.go
- x/typesutil/check_test.go
fix: https://github.com/nighca/builder-experience/issues/32
1. When processing the inner expr, panic occurs.
2. The corresponding stmt does not call end.
3. This lack of an end causes the code context to not be restored to the old code context.
4. Ultimately, when the outer stmt processes the remaining expr, the code context is incorrectly verified, causing another panic.
> fix(typesutil): fix type checker returned an unexpected error

- x/typesutil/check.go
- x/typesutil/gopinfo.go
types.Error does not have End, but has go116end. If the language server needs to use end, it must use reflection, which has poor performance. Alternatively, it can use the unsafe package, which is also not very safe. Therefore, xgo is considering providing its own Error.
> fix(typesutil): use xgo types error

- cl/classfile.go
- cl/cltest/cltest.go
- cl/compile.go
- cl/compile_spx_test.go
fixed: https://github.com/goplus/builder/issues/2047
After we use embed, we no longer need to use autobinding. If we continue to write a variable that duplicates the embed 
field, we expect an error to be reported in advance instead of panicking when Newstruct is reached.
> feat(cl): add check function to embed method for conditional field addition
