goplus/xgo

- README.md
- exec.v2/call.go
- qlang.v2/class2.go
- qlang.v2/function_test.go
- qlang.v2/qlang2.go
- qlang/builtin/number.go
- qlang/reflect/reflect.go
- tutorial/calc/calc.ql
- tutorial/qlang/qlang.ql
> Release v2.2.01

- exec.v2/class.go
- qlang.spec.v1/spec.go
- qlang/meta/meta.go
- qlang/qlang.all/all.go
为qlang添加一些自省功能
fntable  导出 qlang.FnTable （隐藏$名称）
fnlist     导出 qlang.FnTable 的名称列表 （隐藏$名称）
pkglist  导出Go实现的模块列表
dir        列表对象，包括 gopkg, class, class object。
> add qlang meta module

- .travis.yml
- app/qexport/README.md
- app/qexport/main.go
- app/qexport/vendor/github.com/visualfc/goapi/LICENSE
- app/qexport/vendor/github.com/visualfc/goapi/README.md
- app/qexport/vendor/github.com/visualfc/goapi/goapi.go
- app/qexport/vendor/github.com/visualfc/goapi/goapi_test.go
> add qexport for export go package to qlang module

- app/qexport/README.md
- app/qexport/main.go
更新文档
允许使用默认context
允许覆盖默认contexts
> update context flag and doc

- app/qlang/main.go
for issues
https://github.com/qiniu/qlang/issues/70
> add readline support for qlang

- exec.v2/call.go
- qlang.v2/qlang_test.go
> Release v2.7.20

- app/qlang/main.go
> qexport ^C abort input, ^D empty input for exit

- README_QL.md
- exec.v2/class.go
- qlang.v2/class2_test.go
- qlang.v2/qlang2.go
- qlang.v2/qlang_test.go
#98 new ident => new type
#84 #95 README
> Release v2.8.20

- exec.v2/call.go
- qlang.spec.v1/spec.go
- qlang/net/http/http.go
- qlang/strings/strings.go
> Release v2.9.01

- app/qexport/README.md
- app/qexport/main.go
- qlang/meta/meta.go
const and var title
struct title
struct/interface NewType to type func, if NewType only once
func lower case
qmeta dir and doc support []slice
> qexport update to qlang style export

- README.md
- README_QL.md
- app/qlang/main.go
- exec.v2/call.go
- qlang.spec.v1/spec.go
- qlang/net/http/http.go
- qlang/qlang.all/all.go
- qlang/strings/strings.go
- qlang/terminal/terminal.go
#108 NewTypeEx
#111 qexport update to qlang style export
#78 qlang shell: multi line code
> Release v2.9.10

- README.md
This package adds the support of [Qiniu Q language](https://github.com/qiniu/qlang) in Atom, with syntax highlighting.
Atom Package: https://atom.io/packages/language-q
```
apm install language-q
```
Or Settings/Preferences ➔ Packages ➔ Search for `language-q`
> Add the support in Atom with syntax highlighting.

- README.md
- cmd/eql/example/$set.v1/README.md.eql
- cmd/eql/example/stringset.v1/README.md
- cmd/eql/example/uint32set.v1/README.md
- exec/call.go
- exec/types.go
#131 fix 常表达式优化带来的 bug
#129 fix Link broken in README
> Release v3.2.00

- exec/call.go
- #135 bugfix: 回调函数返回值不支持 error 类型
> Release v3.3.00

- README.md
- cl/var_test.go
- exec/code.go
- qlang/builtin/builtin.go
#142 support undefined[something]
> Release v4.0.00

- cmd/qexport/README.md
- cmd/qexport/main.go
qexport: add export -casestyle, 0:upper, 1:lower, 2:both export, default 0
> qexport: add export -casestyle

- ast/ast.go
- ast/ast_ql.go
- ast/ast_test.go
- ast/astutil/ast_utils.go
- ast/commentmap.go
- ast/commentmap_test.go
- ast/example_test.go
- ast/filter.go
- ast/filter_test.go
- ast/import.go
- ast/issues_test.go
- ast/print.go
- ast/print_test.go
- ast/resolve.go
- ast/scope.go
- ast/walk.go
- cl/expr.go
- cl/expr_test.go
- parser/interface.go
- parser/parse.go
- parser/parse_test.go
- parser/parser.go
- tutorial/07-MapLit/maplit.ql
- tutorial/08-SliceLit/slicelit.ql
> V1.6: tutorial/08-SliceLit

- ast/ast_ql.go
- cl/compile.go
- cl/expr.go
- cl/expr_test.go
- cl/stmt.go
- cl/type_decl.go
- exec/code.go
- exec/context.go
- exec/func.go
- exec/gopkg.go
- exec/gopkg_test.go
- lib/builtin/exports.go
- lib/strings/exports.go
- parser/interface.go
- parser/parse_test.go
- parser/parser.go
- parser/parser_test.go
- tutorial/10-List-Comprehension/list.ql
- parse ListComprehension/MapComprehension
- tutorial/10-List-Comprehension
> List Comprehension

- README.md
- cl/expr.go
- cl/stmt_test.go
- tutorial/04-Func/func.ql
- tutorial/05-Closure/closure.ql
- tutorial/13-Builtin-Typecast/builtin_and_typecast.ql
- Builtin and typecast
- pass func/closure as func params
> pass func/closure as func params

- cl/expr.go
- cl/stmt.go
- exec.spec/interface.go
- exec/bytecode/const_test.go
- exec/bytecode/func.go
- exec/bytecode/func_test.go
- exec/bytecode/gopkg_test.go
- exec/bytecode/interface.go
- exec/bytecode/var_test.go
- exec/golang/builder.go
- exec/golang/builder_test.go
- exec/golang/expr.go
- exec/golang/func.go
- exec/golang/interface.go
- exec/golang/stmt.go
- exec/golang/testdata/11.for-loop/for.ql
- exec/golang/testdata/12.flow/flow.ql
- exec/golang/testdata/13.func/func.ql
- exec/golang/testdata/14.closure/closure.ql
- exec/golang/type.go
- exec/golang/var.go
- Label/Jmp/JmpIf/CaseNE/Default
- DefineFunc/EndFunc/Load/Store
- support fmt.Println(fmt.Println())
- TODO: closure bug to be fixed
> flow & func

- cl/compile.go
- cl/compile_test.go
- cl/type_decl.go
- cl/value.go
- cmd/qgo/qgo.go
- cmd/qrun/qrun.go
- exec/bytecode/func.go
- exec/bytecode/func_test.go
- exec/golang/builder.go
- exec/golang/builder_test.go
- exec/golang/gogen_test.go
- exec/golang/testdata/15.pkg/foo.ql
- tutorial/14-Using-qlang-in-Go/gomain/main.go
- tutorial/14-Using-qlang-in-Go/qlfoo/foo.ql
- Package.Find
- Context.Call(fun FuncInfo)
- NewPackage.PkgAct: PkgActClAll
- tutorial/14-Using-qlang-in-Go
> library package support (non-main package)

- README.md
- exec/bytecode/func_test.go
> Using qlang in Go

- ast/ast.go
- ast/ast_ql.go
- ast/astutil/ast_utils.go
- ast/commentmap.go
- ast/filter.go
- ast/import.go
- ast/print.go
- ast/resolve.go
- ast/scope.go
- cl/check_type.go
- cl/ctx_check.go
- cl/expr.go
- cl/expr_test.go
- cl/goinstr.go
- cl/value.go
- exec/bytecode/operator.go
- exec/bytecode/var.go
- exec/golang/testdata/16.unary/unary_tilde.ql
- parser/parse.go
- parser/parse_test.go
- parser/parser.go
- scanner/errors.go
- scanner/scanner.go
- token/position.go
- token/token.go
- scanner
- unaryOp/boundConst
- TestTILDE
> scanner; unaryOp/boundConst/TestTILDE

- cl/compile_test.go
- cl/expr.go
- cmd/qgo/qgo.go
- exec.spec/interface.go
- exec/bytecode/code.go
- exec/bytecode/context.go
- exec/bytecode/flow.go
- exec/bytecode/flow_test.go
- exec/bytecode/gopkg.go
- exec/bytecode/interface.go
- exec/golang/builder_test.go
- exec/golang/gogen_test.go
- exec/golang/interface.go
- exec/golang/stmt.go
- exec/golang/testdata/17.ternary/ternary.gop
- tutorial/15-ErrWrap/err_wrap.gop
- opWrapIfErr
- exec/golang.ErrWrap/WrapIfErr
> opWrapIfErr; exec/golang.ErrWrap/WrapIfErr

- cl/cltest/cltest.go
- cl/compile.go
- cl/compile_test.go
- cl/testdata_test.go
- cmd/qrun/qrun.go
- exec.spec/interface.go
- exec/bytecode/code_test.go
- exec/bytecode/const_test.go
- exec/bytecode/context.go
- exec/bytecode/func.go
- exec/bytecode/func_test.go
- exec/bytecode/goinstr.go
- exec/bytecode/gopkg_test.go
- exec/bytecode/interface.go
- exec/bytecode/module.go
- exec/bytecode/profile.go
- exec/bytecode/struct.go
- exec/bytecode/testdata_test.go
- exec/bytecode/var.go
- exec/bytecode/var_test.go
- exec/golang/interface.go
- tutorial/16-Fib/fib.gop
- Context refactor
- exec.Interface => exec.Package
- github.com/qiniu/goplus/cl/cltest
> Context refactor

- exec/golang/builder_test.go
- exec/golang/expr.go
- exec/golang/stmt.go
exec/golang: implement LoadGoVar/StoreGoVar/AddrGoVar
> exec/golang: implement LoadGoVar/StoreGoVar/AddrGoVar

- cl/expr.go
- cl/gopkg_test.go
- cl/value.go
https://github.com/qiniu/goplus/commit/8334c9e1934f78ef8b922f87161c27e10c32353c
修改了constVal.boundKind() 的 ConstUnboundInt 处理以通过测试
> gopkg const support

- ast/astutil/ast_utils.go
- ast/spec/lang_spec.go
- cl/expr.go
- cl/expr_test.go
- cl/value.go
- exec.spec/kind.go
- exec.spec/operator.go
- exec/bytecode/exec_addrop_autogen.go
- exec/bytecode/exec_autogen_test.go
- exec/bytecode/exec_op_autogen.go
- exec/bytecode/flow_test.go
- exec/bytecode/operator.go
- exec/bytecode/operator_test.go
- exec/bytecode/var.go
- exec/golang/expr.go
- exec/golang/var.go
- parser/parse_test.go
- parser/parser.go
- scanner/scanner.go
- token/token.go
- token.RAT
- parser: println(5/7r + 3.4r)
- exec/bytecode: BigInt/BigRat/BigFloat
> token.RAT; parser; exec/bytecode: BigInt/BigRat/BigFloat

- cl/ctx_check.go
- cl/expr.go
- cl/stmt.go
- cl/stmt_test.go
- exec/golang/testdata/20.inc-dec/inc_dec.gop
- exec/golang/var.go
- tutorial/19-IncDec/inc_dec.gop
both qrun and qgo are ok
> a,b:=2,3
> a++
> b--
> println(a,b)
> support Inc dec

- cl/ctx_check.go
- cl/stmt.go
- cl/stmt_test.go
- exec/golang/testdata/11.for-loop/for.gop
- tutorial/12-For-loop/for.gop
```go
sum := 0
arr := [1,3,5,7]
for i := 0; i < len(arr); i++ {
sum+=arr[i]
}
println(sum)
```
> Normal for stmt

- README.md
Check the grammar of README.md with help from Grammarly.com.
> English grammar checking of README.md

- parser/parse.go
36ac37becfc2e1eb7bdf39d5fcde16c8df9b13ca
> fix: when last line is comment parsing will fail

- exec/golang/testdata/01.const/bar.gop
- exec/golang/testdata/03.import/import.gop
- exec/golang/testdata/05.maplit/maplit.gop
- exec/golang/testdata/09.list-comprehens/list_comprehens.gop
- exec/golang/testdata/11.for-loop/for.gop
- exec/golang/testdata/12.flow/flow.gop
- exec/golang/testdata/13.func/func.gop
- exec/golang/testdata/14.closure/closure.gop
- exec/golang/testdata/15.pkg/foo.gop
- exec/golang/testdata/19.rational/rational.gop
- exec/golang/testdata/20.inc-dec/inc_dec.gop
- exec/golang/testdata/21.for-range/for.gop
> exec/golang/testdata: format

- cmd/qgo/qgo.go
> fix #291, qgo returns non-zero when fail

- cl/stmt.go
- cl/stmt_test.go
- exec/golang/testdata/11.for-loop/for.gop
- tutorial/12-For-loop/for.gop
```go
sum := 0
m := {3: 8}
arr := [11, 22]
for arr[0], arr[1] = range m {
sum += arr[0] + arr[1]
}
println(arr[0])
println(arr[1])
println(sum)
```
qrun result:3,8,11
qgo
```go
package main
import fmt "fmt"
var (
sum int
m   map[int]int
arr []int
)
func main() {
//line ./a.gop:1
sum = 0
//line ./a.gop:2
m = map[int]int{3: 8}
//line ./a.gop:3
arr = []int{11, 22}
//line ./a.gop:4
for _gop_k, _gop_v := range m {
//line ./a.gop:4
arr[0], arr[1] = _gop_k, _gop_v
//line ./a.gop:5
sum += arr[0] + arr[1]
}
//line ./a.gop:7
fmt.Println(arr[0])
//line ./a.gop:8
fmt.Println(arr[1])
//line ./a.gop:9
fmt.Println(sum)
}
```
go run reusult is the same as qrun
> Range assign

- cmd/qexp/gopkg/exporter.go
- cmd/qexp/gopkg/exporter_test.go
fixed https://github.com/qiniu/goplus/issues/341
> cmd/qexp/gopkg: simpleType, export func isMethod => execm

- cmd/qrun/qrun.go
- parser/parse.go
- parser/parse_test.go
- tutorial/20-Unix-Shebang/shebang.gop
> Revert "Remove "gop" suffix"

- cl/compile.go
- cl/ctx_check.go
- cl/stmt.go
- cl/stmt_test.go
- cl/type_decl.go
- exec/golang/testdata/12.flow/flow.gop
- tutorial/09-IfElse-SwitchCase/flow.gop
support very basic goto-label statement , ignore some syntax checks.
> Goto label flow

- cl/compile.go
- cl/stmt_test.go
- exec/golang/testdata/12.flow/flow.gop
- tutorial/21-Break-continue-goto/flow.gop
> Goto label bug fixed

- cmd/qfmt/qfmt.go
qfmt should support input source from stdin,  vscode extension required
like gofmt is support it
> support qfmt from stdin

- .pre-commit-config.yaml
- .travis.yml
- cmd/qfmt/qfmt.go
- exec/golang/testdata/08.builtin/builtin.gop
- exec/golang/testdata/09.list-comprehens/list_comprehens.gop
1. must be formatted (find ./ -type f -name "*.gop"|xargs -n 1 qfmt -w)
2. qrun and go run have same results :(qgo -test ./exec/golang/testdata)
3. remove no-go-testing as we use go/testing as default test suits
> pre merge checks

- ast/ast.go
- cl/compile.go
- parser/parse.go
- printer/nodes.go
- printer/printer.go
Fix https://github.com/qiniu/goplus/issues/393
> Rename HasUnnamed into NoEntrypoint

- cl/compile.go
- cl/expr_test.go
- cl/stmt.go
- cl/stmt_test.go
- exec/golang/testdata/11.for-loop/for.gop
- exec/golang/testdata/12.flow/flow.gop
- tutorial/21-Break-continue-goto/flow.gop
this pr is same as #379, i made a wrong rebase of that branch
> Break continue to merge

- lib/default.go
- lib/log/gomod_export.go
> feat: added lib/log

- cl/compile.go
- cl/ctx_check.go
- cl/expr.go
- cl/gopkg_test.go
只是 pkg var 变量本身的读取和写入，不支持 field 操作.
目前的实现是在 blockCtx 中加入 checkLHS  以对 array 单独处理，可能存在问题，需要继续测试。
> pkg.var load and store

- cl/compile.go
- cl/ctx_check.go
- cl/expr.go
- cl/gopkg_test.go
> Redo "pkg.var load and store"

- cl/stmt_test.go
> Cltest stmt #460

- .travis.yml
- cmd/internal/export/gopkg/exporter.go
- exec/golang/testdata/23.stdout/stdout.gop
- lib/io/gomod_export.go
- lib/io/ioutil/gomod_export.go
- lib/log/gomod_export.go
- lib/reflect/gomod_export.go
- lib/strconv/gomod_export.go
- lib/strings/gomod_export.go
- lib/sync/atomic/gomod_export.go
- lib/sync/gomod_export.go
fix a bug at cmd/internal/export/gopkg/exporter.go L:292.
> Gop export bug fixed and re export some go packages

- cl/cltest/testing.go
- cl/ctx_check.go
- cl/expr.go
- cl/expr_test.go
- cl/stmt_test.go
- cl/value.go
- exec/bytecode/const.go
- go.mod
- go.sum
- lib/bytes/gomod_export.go
- lib/default.go
https://github.com/goplus/gop/issues/474
> Auto Property

- cl/compile.go
- cl/expr.go
- cl/stmt.go
- cl/stmt_test.go
- exec.spec/interface.go
- exec/bytecode/code.go
- exec/bytecode/context.go
- exec/bytecode/goinstr.go
- exec/golang/func.go
- exec/golang/testdata/12.flow/flow.gop
- exec/golang/testdata/12.flow/return_flow.gop
```go
for k, v <- [1, 2, 3] {
if k < 2 {
continue
}
if k > 2 {
break
}
println(k, v)
}
```
> continue and break in range flow without label

- cl/context.go
- cl/ctx_check.go
- cl/expr.go
- cl/stmt.go
- cl/stmt_test.go
- exec.spec/interface.go
- exec/bytecode/interface.go
- exec/golang/interface.go
- exec/golang/stmt.go
- exec/golang/testdata/01.const/bar.gop
- exec/golang/testdata/01.var-const/var_const.gop
- exec/golang/var.go
try to fix var scope bug at #303 and #304
> Var scope issues

- cmd/internal/export/gopkg/export.go
- cmd/internal/export/gopkg/exporter_test.go
gop export github.com/qiniu/x/log
gop export github.com/qiniu/x@v1.11.5/log
> qexp: fix export mod pkg with version

- exec.spec/interface.go
- exec/bytecode/code.go
- exec/bytecode/goinstr.go
- exec/bytecode/goinstr_test.go
- exec/bytecode/interface.go
- exec/golang/builder_test.go
- exec/golang/expr.go
- exec/golang/interface.go
bytecode & golang: AddrIndex
```
&a[0]
```
> exec: add AddrIndex

- cmd/internal/export/export.go
- cmd/internal/export/golist.go
- cmd/internal/export/srcimporter/srcimporter.go
fix pkg/... if pkg root empty, export go/... pass.
fix cgo types-check, export fyne.io/fyne@latest/... pass
ignore pkg for imports has internal/vendor pkg, export golang.org/x/tools@latest/go/... pass
> cmd: export fix cgo types-check, ignore has internal/vendor imports pkg.

- cmd/internal/repl/repl.go
fix set src source code order on defer
> cmd: repl fix src error set on panic

- cl/stmt.go
- exec/golang/builder.go
- exec/golang/stmt.go
- exec/golang/testdata/12.flow/flow.gop
- exec/golang/var.go
> labels in scopeCtx not builder

- cl/ctx_check.go
- exec/golang/testdata/11.for-loop/for.gop
> ast.ParenExpr  isNoExecCtxExpr fixed

- cl/expr.go
- cl/gopkg_test.go
fix fieldExpX check for field on golang generate.
> cl: fix load/store field expr check

- cl/expr.go
- cl/expr_test.go
- cl/gopkg_test.go
support take address value&field
```
Go+ -> generate Golang
&array[0] -> &(&array)[0]
&slice[0] -> &slice[0]
&map[0] : panic cannot take the address
```
Go+ code
```
import "image"
type Point struct {
X int
Y int
}
pt := Point{10,20}
println(&pt)
println(&pt.X)
m := {1:"hello",2:"world"}
println(&m)
//println(&m[1]) // panic cannot take the address of m[1]
ar := [2]Point{Point{10,20},Point{100,200}}
println(&ar)
println(&ar[0])
println(&ar[0].X)
rcs := [image.Rect(1,1,10,10),image.Rect(2,2,20,20)]
println(&rcs)
println(&rcs[0])
println(&rcs[0].Min)
println(&rcs[0].Min.X)
rc := image.Rect(10,20,100,200)
println(&rc)
println(&rc.Min)
println(&rc.Min.X)
println(&image.ZR)
println(&image.ZR.Min)
println(&image.ZR.Min.X)
```
```
package main
import (
fmt "fmt"
image …
```
> cl: take address value and field

- cl/expr.go
- cl/gopkg_test.go
- cl/type_decl.go
- cmd/internal/export/gopkg/export.go
- cmd/internal/export/gopkg/exporter.go
- lib/bytes/gomod_export.go
- lib/default.go
- lib/flag/gomod_export.go
- lib/fmt/gomod_export.go
- lib/github.com/goplus/gop/ast/gopq/gomod_export.go
- lib/io/gomod_export.go
- lib/log/gomod_export.go
- lib/os/gomod_export.go
- lib/reflect/gomod_export.go
- lib/strconv/gomod_export.go
- lib/strings/gomod_export.go
- lib/sync/atomic/gomod_export.go
- lib/sync/gomod_export.go
- lib/time/gomod_export.go
qexp: support export type
cl: support external type
Go+ code
```
import "image"
println(image.Point{10,20})
println(image.Point{X:10,Y:20})
println(&image.Point{10,20})
println(&image.Point{X:10,Y:20})
println(image.Rectangle{image.Point{1,1},image.Point{100,200}})
println(image.Rectangle{Min:image.Point{1,1},Max:image.Point{100,200}})
println(&image.Rectangle{image.Point{1,1},image.Point{100,200}})
println(&image.Rectangle{Min:image.Point{1,1},Max:image.Point{100,200}})
```
```
package main
import (
fmt "fmt"
image "image"
)
func main() { 
//line ./main.gop:3
fmt.Println(image.Point{X: 10, Y: 20})
//line ./main.gop:4
fmt.Println(image.Point{X: 10, Y: 20})
//line ./main.gop:5
fmt.Println(&image.Point{X: 10, Y: 20})
//line ./main.gop:6
fmt.Println(&image.Point{X: 10, …
```
> qexp: export type, cl support toExternalType

- cl/context.go
- cl/ctx_check.go
- cl/expr.go
- cl/expr_test.go
- exec/golang/builder.go
- exec/golang/testdata/29.func-set/func.gop
- exec/golang/var.go
- tutorial/27-Func-Set/func.gop
fix bug: https://github.com/goplus/gop/issues/569
**done**
> support starExpr in lhs

- parser/parser.go
- parser/parser_test.go
fix: https://github.com/goplus/gop/issues/429
Previous pr：https://github.com/goplus/gop/pull/464 has a problem:
Use the following code to verify that there is a problem:
```
println([1]int{1}[0])
```
> slice lit has only one element

- cl/ctx_check.go
- cl/stmt.go
- exec/golang/testdata/12.flow/flow.gop
> init condition fixed

- exec/golang/testdata/13.func/func.gop
- parser/parser.go
> parser: fix #573, parser func expected declaration error

- ast/astutil/type.go
- cl/expr.go
- cl/stmt_test.go
- exec/golang/func.go
fix #608, fix #609 support user-defined method and gopkg func to closure
change ast, func to closure `func funcToClosure(ctx *blockCtx, fun ast.Expr, ftyp *ast.FuncType) *funcDecl` 
Go+ method to closure
```
fn := m.Test => fn := func() { m.Test() }
````
gopkg func/method to closure `func FuncType(typ reflect.Type) *ast.FuncType`
clone [exec/golang/type.go](https://github.com/goplus/gop/blob/master/exec/golang/type.go) to [ast/astutil/type.go](https://github.com/visualfc/goplus/blob/varcallx/ast/astutil/type.go)
```
fn := fmt.Println => fn := func(a ...interface{}) { fmt.Println(a...)}
buf := &bytes.Buffer{}
fn := buf.Write => fn := func(arg0 []byte) (int,error) { return buf.Write(arg0) }
```
Go+ code
```
import (
"fmt"
"bytes"
)	
type M struct {
Sym string
}
func (m M) Test(a string, n …
```
> cl: support user-defined method and gopkg func to closure

- ast/ast_ql.go
- cl/expr.go
- cl/expr_test.go
- cl/stmt.go
- exec.spec/interface.go
- exec/bytecode/goinstr_lstcompr.go
- exec/bytecode/goinstr_lstcompr_test.go
- exec/bytecode/gopkg_test.go
- exec/bytecode/interface.go
- exec/golang/interface.go
- exec/golang/testdata/05.maplit/maplit.gop
> Map two value assign

- cl/ctx_check.go
- cl/expr.go
- cl/stmt.go
- cl/stmt_test.go
- exec.spec/interface.go
- exec/bytecode/chan.go
- exec/bytecode/chan_test.go
- exec/bytecode/code.go
- exec/bytecode/context.go
- exec/bytecode/interface.go
- exec/golang/interface.go
- exec/golang/stmt.go
- exec/golang/testdata/32.channel/chan.gop
- exec/golang/type.go
- parser/parser.go
- tutorial/28-channel/chan.gop
**Done**
fix: https://github.com/goplus/gop/issues/614
feature: https://github.com/goplus/gop/issues/278
example: 
```
c := make(chan int, 10)
c <- 3
d := <-c
println(d)  // 3
```
> new feature: support channel

- exec/golang/func.go
- exec/golang/var.go
golang: fix #600 , define var change "_name" to "_q_name"
```
var ident string   => golang: ident
var _ident string  => golang: _q_ident
```
Go+ code
```
import (
"fmt"
"strconv"
)
type M struct {
_recv string
}
func (m M) Test() {
_recv := "hello"
println(m,_recv,m._recv)
}
func foo(a string) int {
_arg_0 := "hello"
_ret_1 := "ret"
println(a)
println(_arg_0,_ret_1)
return 100
}
func add(x, y string) (int, error) {
return strconv.Atoi(x)? + strconv.Atoi(y)?, nil
}
println(add("100", "23")!)
_gop_1 := "hello"
println(_gop_1)
foo("#")
m := M{"#"}
m.Test()
```
```
package main
import (
fmt "fmt"
errors "github.com/qiniu/x/errors"
strconv "strconv"
)
type M struct {
_recv string
}
var (
_q_gop_1 string
m        M
)
func main() { 
//line ./main.gop:28
_gop_1, _gop_2 := …
```
> golang: fix #600, define var change '_name' to '_q_name'

- cmd/internal/export/gopkg/exporter.go
- cmd/internal/export/gopkg/exporter_test.go
fix https://github.com/goplus/gop/issues/632
```
gop export github.com/pelletier/go-toml@latest
```
> export: fix #632, fixPkgString regexp add - and _

- exec.spec/operator.go
- exec/bytecode/exec_addrop_autogen.go
BigInt addr operator  += -= *= /= + --
> bytecode: add builtinAddrOps for BigInt

- exec/golang/testdata/19.rational/rational.gop
- exec/golang/var.go
- go.sum
Go+ code
```
for i := 1r; i < 10r; i++ {
println(i)
}
```
```
package main
import (
fmt "fmt"
big "math/big"
)
func main() {
{
var i *big.Int
//line ./main.gop:2
i = big.NewInt(1)
//line ./main.gop:2
goto _gop_1
_gop_1:
//line ./main.gop:2
if !(i.Cmp(big.NewInt(10)) < 0) {
goto _gop_2
}
//line ./main.gop:3
fmt.Println(i)
//line ./main.gop:2
goto _gop_3
//line ./main.gop:2
goto _gop_3
_gop_3:
//line ./main.gop:2
i.Add(i, big.NewInt(1))
//line ./main.gop:2
goto _gop_1
//line ./main.gop:2
goto _gop_2
_gop_2:
}
}
```
> golang: support inc/dec for BigInt/BigRat/BigFloat

- README.md
It's a jupyter kernel for Go+
Close #314
> Add gopyter link

- cl/expr.go
- cl/expr_test.go
- cl/type_decl.go
- exec/bytecode/var.go
- exec/golang/var.go
fix #668 
fix #669 
fix #670 
fix #671
> fix #668 #669 #670 #671 load addr and slice/array error

- cl/stmt.go
- cl/stmt_test.go
> fix fallthrough bug

- cl/compile_test.go
- cl/func_type_and_var.go
> fix method recv is nil named param check

- cl/compile_test.go
- cl/error_msg_test.go
- cl/expr.go
> compileIdentLHS: use lookupParent

- README.md
- cl/compile.go
- cl/compile_test.go
- tutorial/36-Auto-Property/autoprop.gop
> Simplify module imports

- ast/ast_gop.go
- parser/_testdata/rangeexpr/parser.expect
- parser/_testdata/rangeexpr/rangeexpr.gop
- parser/parser.go
- tutorial/43-RangeExpr/rangeexpr.gop
> parseRangeExpr

- ast/ast_gop.go
- builtin/range.go
- cl/builtin.go
- cl/expr.go
- parser/_testdata/rangeexpr/parser.expect
- parser/parser.go
- printer/nodes.go
- tutorial/43-RangeExpr/rangeexpr.gop
> for range `start:end:step` support step < 0

- all.bash
1. Clear gop cache files when rerun `all.bash`
2. Fix mistake path when executing commands.
> Clear gop cache

- .github/workflows/go.yml
- all.bash
Update github action to use `all.bash` script.
Make all scripts in one place, easier to maintain.
> Optimize GitHub action script

- cl/compile.go
- cl/compile_test.go
- cmd/goptestgo/goptestgo.go
- go.mod
- go.sum
#808: support type instruction
> TestGoTypeInstr

- ast/ast.go
- ast/filter.go
- cl/compile.go
- cl/error_msg_test.go
- cmd/gopfmt/gopfmt.go
- format/internal.go
- parser/_testdata/gmxtest/parser.expect
- parser/_testdata/spxtest/parser.expect
- parser/_testdata/stdtype/parser.expect
- parser/interface.go
- parser/parser.go
- parser/parser_gop.go
- parser/parser_test.go
- printer/nodes.go
fix #331
remove `parseFileEx`
add `(*parser).parseDeclEx`
> parser: remove parseFileEx func

- x/mod/modfile/read.go
- x/mod/modfile/read_test.go
- x/mod/modfile/rule.go
- x/mod/modfile/rule_test.go
- x/mod/modfile/testdata/block.golden
- x/mod/modfile/testdata/block.in
- x/mod/modfile/testdata/comment.golden
- x/mod/modfile/testdata/comment.in
- x/mod/modfile/testdata/gopkg.in.golden
- x/mod/modfile/testdata/module.golden
- x/mod/modfile/testdata/module.in
- x/mod/modfile/testdata/replace.golden
- x/mod/modfile/testdata/replace.in
- x/mod/modfile/testdata/replace2.golden
- x/mod/modfile/testdata/replace2.in
- x/mod/modfile/testdata/retract.golden
- x/mod/modfile/testdata/retract.in
- x/mod/modfile/testdata/rule1.golden
- x/mod/modfile/testdata/work/comment.golden
- x/mod/modfile/testdata/work/comment.in
- x/mod/modfile/testdata/work/replace.golden
- x/mod/modfile/testdata/work/replace.in
- x/mod/modfile/testdata/work/replace2.golden
- x/mod/modfile/testdata/work/replace2.in
- x/mod/modfile/testdata/work/use.golden
- x/mod/modfile/testdata/work/use.in
- x/mod/modfile/work.go
- x/mod/modfile/work_test.go
Use the latest modfile version and test
> add modfile test

- cl/compile_test.go
- cl/expr.go
> cl: lambda support return values

- cl/compile_test.go
- cl/expr.go
- cl/stmt.go
fix https://github.com/goplus/gop/issues/937
> cl: support print/println cmd no params call

- cl/compile_test.go
- cl/expr.go
- cl/stmt.go
> Revert "cl: support print/println cmd no params call"

- cl/compile_test.go
- cl/stmt.go
fix https://github.com/goplus/gop/issues/937
> cl: fix print/println cmd no params call

- all.bash
- cmd/install.go
1. Support uninstall gop
2. Optimize cmd/install.go
3. Remove auto generated `cmd` bin file
> Support uninstall gop, optimize cmd/install.go, remove auto generated cmd bin file

- build/build.go
- cmd/internal/run/path.go
- cmd/internal/run/path_test.go
- cmd/internal/run/run.go
Find order:
0. Parent directories of the directory
1. Check $GOPROOT, panic if it's invalid
2. The parent directory of the executable
3. Check build.GopRoot
4. Check $HOME/gop/, $HOME/goplus/
> Find mod file in gop root

- cmd/internal/modload/modload.go
If gop.mod does not exist, then modroot does not exist, and if go.mod exists in the current directory, then a copy of go.mod will be synchronized to gop.mod
> if gop.mod does not exist, but go.mod exist,auto sync to gop.mod

- cmd/internal/modload/modload.go
look for enclosing gop.mod and go.mod
> look for enclosing gop.mod and go.mod

- x/mod/modfile/rule_test.go
> fix gopstmt test case

- cmd/gop/main.go
- cmd/internal/env/env.go
Doesn't support `-u`, `-w` yet.
> Add gop env command

- .gitattributes
- parser/parserdir_test.go
- printer/gop_test.go
- x/mod/modfile/read_test.go
Maybe need a full specification of the eol style.
> Fix tests on Windows

- cmd/gopfmt/gopfmt.go
- cmd/internal/gopfmt/fmt.go
- format/format.go
- printer/gop_test.go
- x/format/gopstyle.go
- x/format/gopstyle_test.go
fix https://github.com/goplus/gop/issues/1020
> fix gopfmt & gop fmt report error

- cmd/gopfmt/gopfmt.go
- cmd/internal/gopfmt/fmt.go
- cmd/make.go
- format/format.go
- parser/_testdata/cmdlinestyle3/cmd3.gop
- parser/_testdata/cmdlinestyle3/parser.expect
- parser/parserdir_test.go
- printer/gop_test.go
- x/format/gopstyle.go
- x/format/gopstyle_test.go
new features:
- gop/x/format
- build multi platform targets
changes:
- for range `start:end:step` optimization (#875)
- mv cmd/install.go => cmd/make.go
- fix the problem that the path to get the class file gop.mod is wrong
> Release v1.0.33

- x/format/gopstyle.go
- x/format/gopstyle_test.go
processed:
* fmt.Print
* fmt.Printf
* fmt.Println
cases handled:
* variables, like `var _ fmt.Stringer`
* assignments, like `_ = fmt.Errorf(...)`
* func calls, like `fmt.Println(...)`
> feat: convert go code style to go+ code style #1010

- x/format/README.md
- x/format/format.go
- x/format/gopstyle.go
- x/format/gopstyle_test.go
- x/format/stmt_expr_or_type.go
- fmtToBuiltin
- commandStyleFirst
- fncallStartingLowerCase
> format gopstyle

- cl/stmt.go
> cl: remove isBuiltinAutoCall

- cmd/gop/main.go
- cmd/internal/bug/bug.go
- cmd/internal/env/env.go
> feat: implement gop bug command

- x/gopproj/gopfiles.go
> bug fixed // import builtin

- cl/builtin.go
- cl/compile_test.go
fix https://github.com/goplus/gop/issues/1070
> cl: builtin add type alias any = interface{}

- x/gopproj/gopfiles.go
demo/hello.gop
if not found go.mod use `gop run hello.gop` panic.
fixed: if not fond go.mod use $HOME/.gop/run/go.mod and set gen work path on $HOME/.gop/run
```
if p.defctx {
wd, _ := os.Getwd()
os.Chdir(modDir)
defer func() {
os.Chdir(wd)
}()
}
```
> x/gopproj: fix gop run file work dir

- parser/_testdata/cmdlinestyle4/cmd4.gop
- parser/_testdata/cmdlinestyle4/parser.expect
- parser/parser.go
fix https://github.com/goplus/gop/issues/1110
> parser: fix funlit  command style single line

- README.md
- builtin/ng/big.go
- builtin/ng/int128.go
- builtin/ng/uint128.go
- cl/compile.go
- cl/expr.go
- cl/run_test.go
- go.mod
- go.sum
- cl: [rename unary + (Gop_Pos => Gop_Dup)](https://github.com/goplus/gop/commit/8a91b246ce353d2cd3ff66f0d0d376b7257dba68)
- cl: [support overload operator ++/--](https://github.com/goplus/gop/commit/e78e9933d67106ba8f6e6d0d75600f79721ff4dd)
- cl: [typecast support twoValue](https://github.com/goplus/gop/commit/53fb12570b0f1f1410357aec296a753f2e7fc3d6)
- cl: [support type() to get zero value](https://github.com/goplus/gox/commit/216aa1c4232a3203ccc43181213139ee4c89616b)
- builtin: [int128/uint128: support `<op>=`](https://github.com/goplus/gop/commit/6f92a1ae00f3b1d3e62eb12dbbc227384fb67a6a)
> v1.1.0-beta3

- cl/compile.go
- cl/compile_spx_test.go
- cl/compile_test.go
- cl/run_test.go
- go.mod
- go.sum
- x/gengo/gengo.go
- x/gopproj/gopfiles.go
> Revert "gox v1.11.3"

- cl/compile.go
- cl/compile_spx_test.go
- cl/compile_test.go
- cl/run_test.go
- go.mod
- go.sum
- x/gengo/gengo.go
- x/gopproj/gopfiles.go
> Revert "Revert "gox v1.11.3""

- cmd/internal/base/pass.go
- cmd/internal/build/build.go
- cmd/internal/install/install.go
- cmd/internal/run/run.go
- cmd/internal/test/test.go
support #1300 
```
func NewPassArgs(flag *flag.FlagSet) *PassArgs
```
```
func PassBuildFlags(cmd *Command) *PassArgs
```
**TODO**
```
func PassTestFlags
```
> gop cmd pass build flags

- cmd/internal/test/test.go
- cmd/internal/test/testflag.go
gop test support go test flags
```
gop test -v -run TestMe
gop test -v -test.run TestMe
```
> cmd/gop: test pass flags

- cl/typeparams_test.go
update test typeparams error msg to go1.20 from go1.20rc1
> fix test typeparams for go1.20

- cl/compile.go
- cl/compile_spx_test.go
- cl/compile_test.go
- cl/error_msg_test.go
- cl/func_type_and_var.go
- parser/_testdata/gopxtest/bar.gopx
- parser/_testdata/gopxtest/parser.expect
- parser/interface.go
- parser/parser.go
- parser/parser_gop.go
- parser/parser_test.go
implement https://github.com/goplus/gop/issues/1371
add default classfile .gopx
support classfile embed type
> cl:parser: support .gopx and classfile embed type

- cmd/make.go
> fix: check isInChina on Windows

- parser/parser.go
fix https://github.com/goplus/gop/issues/1392
> parser: parseValueSpec check gop class pkgScope

- parser/parser.go
- parser/parser_test.go
fix https://github.com/goplus/gop/issues/1412
> parser: fix parseDecl token.FUNC error

- cl/internal/typesutil/api.go
- cl/internal/typesutil/api_test.go
- cl/recorder.go
- go.mod
- x/typesutil/info_test.go
typeRecorder
- type: array/map/struct/chan/interface/func
- typeAssert
- chan arrow
> cl: update typesRecorder api

- cl/expr.go
- cl/stmt.go
- x/typesutil/info_test.go
depends by https://github.com/goplus/gop/pull/1575
> cl: compileComprehensionExpr types record define kv

- .github/workflows/release-build.yml
- .gitignore
- .goreleaser.yaml
Build binaries and publish winget pkg with  with https://github.com/goreleaser/goreleaser
* Build binaries
* Build `GoPlus` winget package
* Commit and push manifests into https://github.com/goplus/winget-pkgs
* Create PR on https://github.com/microsoft/winget-pkgs
TODO:
Preview:
* Test build action: https://github.com/cpunion/gop/actions/runs/7472537673/job/20334931754
* Test Release: https://github.com/cpunion/gop/releases/tag/v1.2.8
* Test winget-pkgs: https://github.com/cpunion/winget-pkgs/tree/gop-v1.2.9/manifests/g/GoPlus/GoPlus/1.2.9
* Test install
> Build and publish winget with goreleaser

- parser/_nofmt/printvariadic/parser.expect
- parser/_nofmt/printvariadic/printv.gop
- parser/parser.go
fix https://play.goplus.org/p/eJyGvfHGjjD
```
println(
a...,
)
```
> parser: fix variadic end comma

- cl/builtin_test.go
- cl/classfile.go
- cl/compile.go
- cl/compile_spx_test.go
- cl/expr.go
- cl/internal/spx3/spx3.go
- cl/stmt.go
- x/build/build_test.go
- x/typesutil/info_test.go
- [this.Sprite.Main(...) or this.Game.MainEntry(...)](https://github.com/goplus/gop/commit/766e6b27235567e45e20ec15ff8930d53f7a28f7)
- [spxClass: Classfname() string](https://github.com/goplus/gop/commit/1abc2bc0e89fe60bdda80981b720c7c8d007e221)
> classfile: Main(...), Classfname()

- .github/workflows/release-build.yml
- Updated go-version to "1.21.x" in actions/setup-go for alignment with go.yml.
- Switched to "${{ github.token }}" for authentication, adhering to GitHub Actions best practices.
- Removed redundant default environment variable settings[^1], simplifying the workflow.
[^1]: https://docs.github.com/en/actions/learn-github-actions/variables#default-environment-variables
> ci(release-build.yml): refine workflow for better consistency and efficiency

- cl/compile_gop_test.go
- go.mod
- go.sum
update gogen for fix https://github.com/goplus/spx/issues/465
> update gogen for overload check untyped args

- x/format/README.md
- x/format/_testdata/collection/format.expect
- x/format/_testdata/syntax/format.expect
- x/format/format.go
- x/format/gopstyle_test.go
> x/format: fmt.println => echo

- demo/gop-parser/pseudo/parser.gop
- demo/gop-scanner/rpncalc/rpncalc.gop
- demo/gop-scanner/simplecalc/calc.gop
> demo: gop-scanner/parser

- cl/builtin.go
- demo/gop-typeof/typeof.gop
- parser/_testdata/typeof/parser.expect
- parser/_testdata/typeof/typeof.gop
- parser/parser.go
> #2115 type as builtin func

- cl/_testgop/domaintpl/in.gop
- cl/_testgop/domaintpl/out.go
- cl/expr.go
- demo/tpl-calc/calc.gop
- demo/tpl-gen-ast/gen_calc_ast.gop
- demo/tpl-vcalc/variant_calc.gop
- tpl/matcher/match.go
- tpl/tpl.go
- tpl/variant/math/math.go
- tpl/variant/module.go
- tpl/variant/time/time.go
- tpl/variant/variant.go
* tpl/variant: module/fncall
* tpl/matcher: Var.Match recover error
* tpl: this => self
> tpl/variant: module/fncall; tpl/matcher: Var.Match recover error; tpl: this => self

- cl/builtin_test.go
- cl/classfile.go
- cl/compile.go
- cl/compile_spx_test.go
- cl/internal/spx3/spx3.go
#2257: Reverts goplus/gop#2255
> Revert "classfile: Classprojname"

- cl/stmt.go
> Revert "cl: comment //line once"

- .github/codecov.yml
- cl/_testgop/domaintext-huh/in.gop
- cl/_testgop/domaintext-huh/out.go
- cl/cltest/cltest.go
- cl/expr.go
- cl/internal/huh/huh.go
- cl/internal/mcp/classfile.go
- parser/_testdata/domainhuh/huh.gop
- parser/_testdata/domainhuh/parser.expect
- parser/parser.go
https://github.com/goplus/gop/issues/2143
> parser: domainTextLitEx; cl: compileDomainTextLit with args

- .github/workflows/release-build.yml
Build passed: https://github.com/cpunion/gop/actions/runs/14924468918/job/41926094797
> release with go1.24

- parser/parser.go
- parser/parser_test.go
fix: https://github.com/goplus/builder/issues/1626
> feat(parser)  enhance parser to determine block statement positions and add tests for shadow entry handling

- .github/codecov.yml
- cl/builtin.go
- cl/compile.go
- cl/compile_gop_test.go
- cl/compile_test.go
- cl/internal/typesalias/alias_go121.go
- cl/internal/typesalias/alias_go122.go
- cl/internal/typesalias/typeparams_go122.go
- cl/internal/typesalias/typeparams_go123.go
- cl/typeparams.go
- cl/typeparams_test.go
- x/typesutil/info_test.go
support Go1.24 aliastypeparams
> cl: support aliastypeparams

- .goreleaser.yaml
Build status: https://github.com/cpunion/xgo/actions/runs/15224246640/job/42824517195
> goreleaser gop => xgo

- cl/_testgop/errwrap2/in.xgo
- cl/_testgop/errwrap2/out.go
- cl/stmt.go
fix https://github.com/goplus/xgo/issues/2419
> cl: compileAssignStmt token.DEFINE check stack

- ast/ast_gop.go
- cl/classfile.go
- cl/compile.go
- cl/error_msg_test.go
- cl/expr.go
- cl/func_type_and_var.go
- cl/stmt.go
- cl/typeparams.go
- go.mod
- go.sum
- x/typesutil/check.go
fix: https://github.com/goplus/builder/issues/2013
> feat(cl): fix the range returned by diagnostic only has start but no end.

- ast/ast.go
- ast/ast_gop.go
- ast/ast_xgo.go
- ast/walk.go
> xgo/ast: add Kwargs []*KwargExpr for CallExpr

- parser/_testdata/kwargs1/kwargs.xgo
- parser/_testdata/kwargs1/parser.expect
- parser/parser_test.go
> TestErrKwargExpr

- cl/_testgop/kwargs1/in.xgo
- cl/_testgop/kwargs1/out.go
- cl/_testgop/kwargs2/in.xgo
- cl/_testgop/kwargs2/out.go
- cl/_testgop/kwargs3/in.xgo
- cl/_testgop/kwargs3/out.go
- cl/_testgop/kwargs4/in.xgo
- cl/_testgop/kwargs4/out.go
- cl/expr.go
- cl/internal/testutil/testutil.go
> xgo/cl: support for kwargs
